---
title: R2integrated
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    metadata:
      title: 
      description: 
    hero:
      class: 'bg-primary ta-center'
      title: 
      intro: 
      cta:
        copy: 
        link: 
permalink: pretty
