---
title: R2integrated
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: default
  values:
    layout: default
    metadata:
      title: ''
      description: ''
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    hero:
      title: ''
      intro: ''
      cta:
        copy: ''
        link: ''
permalink: pretty
