---
title: R2integrated
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    metadata:
      title: 
      description: 
    hero:
      background_class: [bg-primary, bg-secondary, bg-tertiary, bg-primary-lt, bg-secondary-lt, bg-tertiary-lt, bg-accent-1, bg-accent-2, bg-accent-3]
      size_class: [lg, sm, fs]
      alignment_class: [ta-left, ta-center, ta-right]
      title: 
      intro: 
      cta:
        copy: 
        link: 
        class: [btn-primary, btn-secondary, btn-tertiary]
permalink: pretty
